import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { supabaseConfig } from './supabase-config-module.js';

const configured = supabaseConfig?.url && supabaseConfig?.anonKey && !supabaseConfig.url.startsWith('YOUR_') && !supabaseConfig.anonKey.startsWith('YOUR_');
export const supabase = configured ? createClient(supabaseConfig.url, supabaseConfig.anonKey, { auth: { persistSession: true, autoRefreshToken: true } }) : null;
function showConfigError(target) { if (target) { target.textContent = 'Настройте Supabase в js/supabase-config-module.js, чтобы продолжить.'; target.hidden = false; } }
export const profileDisplayName = (profile, email = '') => [profile?.first_name, profile?.last_name].filter(Boolean).join(' ') || email.split('@')[0] || 'Пользователь';
export async function getProfile(userId) { const { data, error } = await supabase.from('profiles').select('*').eq('user_id', userId).maybeSingle(); if (error) throw error; return data; }
export async function ensureProfile(user) { const existing = await getProfile(user.id); if (existing) return existing; const metadata = user.user_metadata || {}; const fullName = metadata.full_name || metadata.name || ''; const [firstName, ...lastName] = fullName.trim().split(/\s+/); const { data, error } = await supabase.from('profiles').insert({ user_id: user.id, first_name: firstName || null, last_name: lastName.join(' ') || null, avatar_url: metadata.avatar_url || metadata.picture || null, profile_completed: false }).select().single(); if (error) throw error; return data; }
export async function getAuthState() { if (!supabase) return null; const { data: { session } } = await supabase.auth.getSession(); if (!session) return null; return { user: session.user, profile: await ensureProfile(session.user) }; }
export async function requireAuth({ requireProfile = true } = {}) { if (!supabase) { showConfigError(document.querySelector('[data-auth-error]')); return null; } try { const state = await getAuthState(); if (!state) { window.location.replace('auth.html'); return null; } if (requireProfile && !state.profile?.profile_completed) { window.location.replace('profile.html?setup=1'); return null; } return state; } catch (error) { console.error('Authentication state failed:', error); showConfigError(document.querySelector('[data-auth-error]')); return null; } }
export async function uploadAvatar(userId, file, fallbackUrl = null) { if (!file) return fallbackUrl; if (file.size > 2 * 1024 * 1024) throw new Error('Размер файла не должен превышать 2 МБ.'); if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) throw new Error('Выберите PNG, JPG или WebP.'); const extension = file.name.split('.').pop().toLowerCase(); const path = `${userId}/${crypto.randomUUID()}.${extension}`; const { error } = await supabase.storage.from('avatars').upload(path, file, { contentType: file.type, upsert: false }); if (error) throw error; return supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl; }
export async function saveProfile(user, values, avatarFile, existingProfile) { const firstName = values.firstName.trim(); const lastName = values.lastName.trim(); const age = Number(values.age); if (!firstName || !Number.isInteger(age) || age < 1 || age > 150) throw new Error('Введите имя и корректный возраст.'); const avatarUrl = await uploadAvatar(user.id, avatarFile, existingProfile?.avatar_url || null); const payload = { user_id: user.id, first_name: firstName, last_name: lastName || null, age, avatar_url: avatarUrl, profile_completed: true, updated_at: new Date().toISOString() }; const { data, error } = await supabase.from('profiles').upsert(payload, { onConflict: 'user_id' }).select().single(); if (error) throw error; document.dispatchEvent(new CustomEvent('profile:updated', { detail: { user, profile: data } })); return data; }
export async function signOut(redirect = 'chat.html') { if (supabase) await supabase.auth.signOut(); window.location.replace(redirect); }
const authMessages = { invalid_credentials: 'Неверный email или пароль.', email_exists: 'Этот email уже зарегистрирован.', user_already_exists: 'Этот email уже зарегистрирован.', network: 'Ошибка сети. Проверьте подключение и повторите попытку.' };
const friendlyError = (error) => authMessages[error?.code] || (/network|fetch/i.test(error?.message || '') ? authMessages.network : error?.message || 'Не удалось выполнить вход.');
export async function signInWithOAuth(provider) { const { error } = await supabase.auth.signInWithOAuth({ provider, options: { redirectTo: new URL('chat.html', window.location.href).href } }); if (error) throw new Error(`Не удалось выполнить вход через ${provider === 'google' ? 'Google' : provider === 'discord' ? 'Discord' : 'GitHub'}.`); }
export async function setupAuthPage() { const error = document.querySelector('[data-auth-error]'); if (!supabase) return showConfigError(error); if (await getAuthState()) return window.location.replace('chat.html'); const form = document.querySelector('#authForm'); const modeButton = document.querySelector('#authMode'); const submit = form.querySelector('button[type="submit"]'); const confirm = document.querySelector('#passwordConfirmField'); const authButtons = document.querySelectorAll('[data-oauth]'); let mode = 'signin'; const setBusy = (busy, button = submit) => { document.querySelectorAll('button').forEach((item) => { item.disabled = busy; }); button.classList.toggle('is-loading', busy); }; const renderMode = () => { const signup = mode === 'signup'; document.querySelector('#authTitle').textContent = signup ? 'Создать аккаунт' : 'С возвращением'; document.querySelector('#authSubtitle').textContent = signup ? 'Начните свой первый диалог в Axsima.' : 'Войдите, чтобы открыть свои чаты.'; submit.textContent = signup ? 'Зарегистрироваться' : 'Войти'; modeButton.textContent = signup ? 'Уже есть аккаунт? Войти' : 'Нет аккаунта? Зарегистрироваться'; confirm.hidden = !signup; form.confirmPassword.required = signup; error.hidden = true; }; modeButton.addEventListener('click', () => { mode = mode === 'signin' ? 'signup' : 'signin'; renderMode(); }); authButtons.forEach((button) => button.addEventListener('click', async () => { setBusy(true, button); error.hidden = true; try { await signInWithOAuth(button.dataset.oauth); } catch (oauthError) { error.textContent = oauthError.message; error.hidden = false; setBusy(false, button); } })); form.addEventListener('submit', async (event) => { event.preventDefault(); const email = form.email.value.trim(); const password = form.password.value; if (mode === 'signup' && password !== form.confirmPassword.value) { error.textContent = 'Пароли не совпадают.'; error.hidden = false; return; } setBusy(true); error.hidden = true; const result = mode === 'signup' ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (result.error) { error.textContent = friendlyError(result.error); error.hidden = false; return; } if (mode === 'signup' && !result.data.session) { error.textContent = 'Проверьте почту и подтвердите адрес, затем войдите.'; error.hidden = false; return; } window.location.replace('chat.html'); }); renderMode(); }
